// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nkno.Dev.Server.Models.DbModels;

public partial class Coffee
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int RoasterId { get; set; }

    public int OriginCountryId { get; set; }

    public int CoffeeTypeId { get; set; }

    public int? RoastId { get; set; }

    public string FlavourNotes { get; set; }

    public int IsDrink { get; set; }

    public virtual CoffeeType CoffeeType { get; set; }

    public virtual Country OriginCountry { get; set; }

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual RoastType Roast { get; set; }

    public virtual RoastersShop Roaster { get; set; }

    public virtual User User { get; set; }
}