// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nkno.Dev.Server.Models.DbModels;

public partial class Country
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Coffee> Coffees { get; set; } = new List<Coffee>();

    public virtual ICollection<RoastersShop> RoastersShops { get; set; } = new List<RoastersShop>();
}