// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nkno.Dev.Server.Models.DbModels;

public partial class ReviewDetail
{
    public int Id { get; set; }

    public string Comments { get; set; }

    public double? Rating5 { get; set; }

    public int? RatingThumbUpDown { get; set; }

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();
}