// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nkno.Dev.Server.Models.DbModels;

public partial class User
{
    public int Id { get; set; }

    public string Username { get; set; }

    public string Name { get; set; }

    public string Location { get; set; }

    public virtual ICollection<Coffee> Coffees { get; set; } = new List<Coffee>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();
}